### ISSUE TITLE
Displaying the distance from clients location to restaurant?

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#104]
Since we calculate the distance between clients location and the restaurants should we display it. I am thinking on people that may want to take advantage of the discount if you collect your food it would be helpful if they know the distance (I know that it is in a straight line ).

**Comment by mishimaltd** [comment]
Hi mate I am capturing this information but not displaying it yet and yes
we should show it

On 19 Sep 2012, at 09:57, bertso notifications@github.com wrote:

Since we calculate the distance between clients location and the
restaurants should we display it. I am thinking on people that may want to
take advantage of the discount if you collect your food it would be helpful
if they know the distance (I know that it is in a straight line ).

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/104.
