### ISSUE TITLE
Shorten the message instructions in Twillio

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#112]
At the moment the messages are a bit too long, it is fine the first time but then with the testing you get a bit fed up of the "Hello you have a new order from Click... please select one.. ". As soon as they here that voice they are going to know who it is.. and as for the instructions a bit of the same once they know how to use it it will make it quite annoying. If I remember well you said to me that you could bypass it by pressing any key as soon as you start listening to the message but since the whole accepting is not working maybe that is the reason? Or am I imagining the last bit?

**Comment by mishimaltd** [comment]
Mate you can press the key to hear the full order at any time and can also
accept or reject at any time. The accepting via Twilio should be working

On 20 Sep 2012, at 15:10, bertso notifications@github.com wrote:

At the moment the messages are a bit too long, it is fine the first time
but then with the testing you get a bit fed up of the "Hello you have a new
order from Click... please select one.. ". As soon as they here that voice
they are going to know who it is.. and as for the instructions a bit of the
same once they know how to use it it will make it quite annoying. If I
remember well you said to me that you could bypass it by pressing any key
as soon as you start listening to the message but since the whole accepting
is not working maybe that is the reason? Or am I imagining the last bit?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/112.

**Comment by bertso** [comment]
That's what I meant, because it's not working maybe that's why couldn't bypass all the greetings :-)The phone in Ramsgate its not ours but it looks fairly modern and the dial mode is tone, besides that I cannot think of anything else. It has worked previously with my London office phone, you may have to give it a try tonight, or I'll use me mobile.

Date: Thu, 20 Sep 2012 07:24:40 -0700

**Comment by mishimaltd** [comment]
Can you test again please?
