### ISSUE TITLE
Removing items from your order

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#129]
They have mentioned, and I think is a good idea, that currently when you remove something from your order removes the whole amount and that it would be great if it removed them one by one so that if you selected 7 cokes but you want 6 you can just take one of instead of remove all and click 6 times again. They where saying something like -1 +1 links. maybe 3, the current cross and -1 and a +1?

**Comment by mishimaltd** [comment]
Yeah sounds good if you are one at a time adding them now it should one at
a time remove. Don't think I have room for three icons do lets just have a
minus for now

On 24 Sep 2012, at 16:33, bertso notifications@github.com wrote:

They have mentioned, and I think is a good idea, that currently when you
remove something from your order removes the whole amount and that it would
be great if it removed them one by one so that if you selected 7 cokes but
you want 6 you can just take one of instead of remove all and click 6 times
again. They where saying something like -1 +1 links. maybe 3, a trash can
and -1 and a +1?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/129.

**Comment by mishimaltd** [comment]
Done
