### ISSUE TITLE
Restaurant closed message not disappearing when restaurant is opened

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#139]
If a restaurant is closed, get the message "Restaurant is currently closed...." in the Your Order section. If you change the opening time for the restaurant so that it is open the your order allows you to make the order ASAP etc but the message saying that it is close still displays.

**Comment by mishimaltd** [comment]
I don't recheck the status on saving, if you add an item does the warning
go away? It's a small fix I think

On 26 Sep 2012, at 22:27, bertso notifications@github.com wrote:

If a restaurant is closed, get the message "Restaurant is currently
closed...." in the Your Order section. If you change the opening time for
the restaurant so that it is open the your order allows you to make the
order ASAP etc but the message saying that it is close still displays.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/139.

**Comment by mishimaltd** [comment]
Fixed
