### ISSUE TITLE
Discount to appear in the search results

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#141]
This is not something that needs to be done now, but it would be good if you can flag one and only one discount to appear in the search results list so that the restaurants can do promotions and the users see them before they open the restaurant document.

**Comment by mishimaltd** [comment]
No problem

On 27 Sep 2012, at 10:15, bertso notifications@github.com wrote:

This is not something that needs to be done now, but it would be good if
you can flag one and only one discount to appear in the search results list
so that the restaurants can do promotions and the users see them before
they open the restaurant document.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/141.
