### ISSUE TITLE
Not sure I follow the use of Ids

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#16]
I have tried to replicate the use of objects in the app and I find myself not understanding the use of Ids in the controllers.
For example in the RestaurantController.java in the save method
        try {
            Restaurant restaurant = JSONUtils.deserialize(Restaurant.class,body);
            restaurant = repository.saveRestaurant(restaurant);
            model.put("success",true);
            model.put("id",restaurant.getId());
        }
the getId() method will always return null because there is no place, or at least I cannot see it, where the id gets set.
On the other hand if the method used was getRestaurantId() it will return the id created by the SequenceGenerator class. Am I missing something here?

**Comment by mishimaltd** [comment]
Hi Mate. The mongo saving bit should have set the id for you. What might be happening is that the serializing and deserializing of the JSON object is setting the id to "" rather than null. The ID has to be null in order for Mongo to see it as a brand new document and set its id correctly. I thought I had fixed this but maybe not, I will check it again. I think it works OK on creating a new Restaurant via the web site so it must be working correctly somewhere.

**Comment by bertso** [comment]
It works, I just had my logging message in the wrong place and you have no logging messages hence I didn't realize. Sorry
