### ISSUE TITLE
way of amending an existing order

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#212]
We need to find a way of amending an order. If someone has ordered a dish and they want it change there should be a way of dealing with this. Unluckily for us, I am not sure how we are going to deal with the financial side of this automatically. It looks to me as if for the time being this will have to be amended manually at TPV admin level. Maybe we need a way of entering comments in the order document, in the admin panel, so that at least we can make a note explaining why the order amount is not what the system is displaying..

**Comment by mishimaltd** [comment]
Ok I don't think that will be too hard. I have added an orders page to the
admin site. Will add stuff on how you can modify the orders next, currently
you can just view and search by order ID or part of order ID

On 28 Oct 2012, at 08:17, bertso notifications@github.com wrote:

We need to find a way of amending an order. If someone has ordered a dish
and they want it change there should be a way of dealing with this.
Unluckily for us, I am not sure how we are going to deal with the financial
side of this automatically. It looks to me as if for the time being this
will have to be amended manually at TPV admin level. Maybe we need a way of
entering comments in the order document, in the admin panel, so that at
least we can make a note explaining why the order amount is not what the
system is displaying..

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/212.

**Comment by bertso** [comment]
Cool. What is it that you don't think it will hard to do? Changing the order manually? 

Date: Sun, 28 Oct 2012 01:26:37 -0700

**Comment by mishimaltd** [comment]
Yeah, we just create a new object called OrderAmendment which has 3
properties, the description of the amendment, the time it was created, and
the new total cost of the order.

The order object can have a list of these amendment objects

On 28 Oct 2012, at 08:32, bertso notifications@github.com wrote:

Cool. What is it that you don't think it will hard to do? Changing the
order manually?

Date: Sun, 28 Oct 2012 01:26:37 -0700

**Comment by bertso** [comment]
Neat. We may need a comments field to specify what the amendment was about.
Comment: A number 23 was replaced with a 7 with prawns.

Date: Sun, 28 Oct 2012 01:38:01 -0700

**Comment by mishimaltd** [comment]
Done
