### ISSUE TITLE
Address fields missing when checking out without registering

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#22]
Currently when checking out without registering you have the fields below:
First name, Last name, Email address, Confirm email address, Telephone, Mobile

I believe that we will need to also:
- House number: Address1
- Street: Address2

At that point we will only have the postcode and that will not be enough to make a delivery

**Comment by mishimaltd** [comment]
Yeah dude its a work in progress :-) I am trying to find a way to tie it all together without seeming to have ripped off someone else's site too much. I quite like the flow of the Domino's site so will probably use that for the general page flow structure and use the hungry house search results. I want to show the current order on every page. 

Basically I am trying to work out how to bring the whole thing together, where are those super Web design dudes? :-)

If I use what Domino's have then there is no need to have a register page because we capture the user's email address anyway and on the Domino's site you can uncheck boxes to say 'Please don't send me any marketing emails'. This way no need to register users at all and we can get user email addresses if we want.

**Comment by bertso** [comment]
Not sure I follow. I understand that by getting the users email address we have a unique identifier for the user but we still need to get the full address to do the delivery. I thought that the whole point of registering was to store the users addresses so that next time they come they don't have to enter them again, unless you are thinking of doing that anyway the first time they place an order and use it subsequently. Is that the plan?

**Comment by mishimaltd** [comment]
I think we just get them to enter the delivery address on each order to start with since they might not be ordering from their home address (although they probably will in 95% of cases). As per my comment on the other issue, so long as the address fields are named appropriately, your browser will auto-fill the address. 

I'd rather not have to deal with either pre-populating the address or having a checkbox which pulls in their home address and stuff as it just adds noise to the page. I order from Domino's a fair amount and have to enter my address each time and it really isn't that much of a chore.

**Comment by bertso** [comment]
I know what you mean

**Comment by mishimaltd** [comment]
Not doing register for first cut so closing this for now
