### ISSUE TITLE
Recognize signed in people in the checkout

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#24]
If you are signed in when checking out it should present a message saying "Welcome back {userName}". Or maybe even better a la Amazon, maybe have an intermediate page, or not, where the user has to confirm if they are the person that its logged in. 
"If you are {userName} go ahead if not log out and log in."

**Comment by mishimaltd** [comment]
I think we can get away without the registration stuff since we require an email address from them in order to place their order. I can make sure that the fields in the delivery/checkout use standard field names so that things like browser autocomplete will pick them up and work (like in Chrome when you start to type an address it gives you the option to auto-populate). Basically makes the app easier to write and I don't think we lose much to be honest.

**Comment by bertso** [comment]
OK

**Comment by mishimaltd** [comment]
Not needed for first realease
