### ISSUE TITLE
Build discounting functionality

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#66]

**Comment by mishimaltd** [comment]
Add a flag to say if a discount can be used in conjunction with other discounts (such as a discount for collection orders). For all discounts not set to be used in conjunction with any others, apply the one which has the highest order value qualifying price that is less than or equal to the order item value.

**Comment by bertso** [comment]
Hi mate,They have looked at the site and they want to know if we can put a header in every page, even if it is in white, so that they can get a feeling of how the space gets redistributed. Maybe time to change the background colour and change the header where home and admin are placed, perhaps use the buttler with the laptop image?Cheers

Date: Thu, 16 Aug 2012 03:01:55 -0700

**Comment by mishimaltd** [comment]
Done

**Comment by bertso** [comment]
Hi mate,
I cannot get to work the bottom frame of the restaurant admin page, whenever I select a menu item, category or discount it does not load the element.I think is because the code is hosted in the Amazon server and its trying to execute in the heroku one. 

Date: Thu, 16 Aug 2012 15:04:22 -0700
