### ISSUE TITLE
Suggestion about Discounts

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#81]
The discounts are not visible to the user until he or she reaches the amount that triggers the discount, could it be worth it to display them somewhere to encourage them to reach that amount?

For example free bottle of wine in orders for 25 euros or more, wouldn't it be a good idea for the user to see that so that it may give them an incentive to reach that amount?

**Comment by mishimaltd** [comment]
I will include details of any discounts in the header but with the
restaurant name and address

On 14 Sep 2012, at 09:29, bertso notifications@github.com wrote:

The discounts are not visible to the user until he or she reaches the
amount that triggers the discount, could it be worth it to display them
somewhere to encourage them to reach that amount?

For example free bottle of wine in orders for 25 euros or more, wouldn't it
be a good idea for the user to see that so that it may give them an
incentive to reach that amount?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/81.

**Comment by mishimaltd** [comment]
Closing as will definitely put on the restaurant menu page
